#!/bin/sh

set -e

# Remove a no-longer used conffile
rm_conffile() {
    local PKGNAME="$1"
    local CONFFILE="$2"

    [ -e "$CONFFILE" ] || return 0

    local md5sum="$(md5sum $CONFFILE | sed -e 's/ .*//')"
    local old_md5sum="$(dpkg-query -W -f='${Conffiles}' $PKGNAME | \
            sed -n -e "\' $CONFFILE ' { s/ obsolete$//; s/.* //; p }")"
    if [ "$md5sum" != "$old_md5sum" ]; then
        echo "Obsolete conffile $CONFFILE has been modified by you."
        echo "Saving as $CONFFILE.dpkg-bak ..."
        mv -f "$CONFFILE" "$CONFFILE".dpkg-bak
    else
        echo "Removing obsolete conffile $CONFFILE ..."
        rm -f "$CONFFILE"
    fi
}

case "$1" in
install|upgrade)
    if dpkg --compare-versions "$2" lt "0.6.26-1"; then
        rm_conffile avahi-dnsconfd "/etc/default/avahi-dnsconfd"
    fi
esac

# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/avahi-dnsconfd" ] && [ ! -L "/etc/init.d/avahi-dnsconfd" ]; then
		if [ "`md5sum \"/etc/init.d/avahi-dnsconfd\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' avahi-dnsconfd | sed -n -e \"\\\\' /etc/init.d/avahi-dnsconfd '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/avahi-dnsconfd has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/avahi-dnsconfd" "/etc/init.d/avahi-dnsconfd.dpkg-bak"
		else
			rm -f "/etc/init.d/avahi-dnsconfd"
		fi
	fi
fi
# End automatically added section

