#!/bin/sh

set -e

case "$1" in
  install|upgrade)
    if dpkg --compare-versions "$2" le "0.6.20-1"; then
      if [ -d "/etc/avahi/etc" ]; then
        rm -f /etc/avahi/etc/localtime;
        rmdir --ignore-fail-on-non-empty /etc/avahi/etc;
      fi
    fi
esac

# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/avahi-daemon" ] && [ ! -L "/etc/init.d/avahi-daemon" ]; then
		if [ "`md5sum \"/etc/init.d/avahi-daemon\" | sed -e \"s/ .*//\"`" != \
		     "`dpkg-query -W -f='${Conffiles}' avahi-daemon | sed -n -e \"\\\\' /etc/init.d/avahi-daemon '{s/ obsolete$//;s/.* //p}\"`" ]
		then
			echo "Obsolete conffile /etc/init.d/avahi-daemon has been modified by you, renaming to .dpkg-bak"
			mv -f "/etc/init.d/avahi-daemon" "/etc/init.d/avahi-daemon.dpkg-bak"
		else
			rm -f "/etc/init.d/avahi-daemon"
		fi
	fi
fi
# End automatically added section


