#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-androideabi-gcc -DOPENSSL_THREADS -I/home/kamil/Repository/comp-lib-support/inx_build_scripts/../target_libs/arm-linux_arm-none-linux-androideabi-9_arm-none-linux-androideabi-9_android-native/build/include/ -I/home/kamil/Repository/comp-lib-support/inx_build_scripts/../../EHS-build-support/support_libs/target_libs/arm-linux-arm-none-linux-androideabi-9/build/include/ -I/home/kamil/Repository/comp-lib-support/inx_build_scripts/../../EHS-build-support/kernel-dependencies/ -I/usr/include -D_REENTRANT -O"
  #define PLATFORM "dist"
  #define DATE "Mon Jul 13 10:34:50 BST 2020"
#endif
